apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
 name: mysql-backupplan
 namespace: mysql
spec:
 backupNamespace: mysql
 backupConfig:
   target:
     name: demo-s3-target
     namespace: default
   schedulePolicy:
     fullBackupPolicy:
       name: trilio-daily-schedule-policy
       namespace: default
 hookConfig:
   mode: Sequential
   hooks:
     - hook:
         name: mysql-hook
       podSelector:
         labels:
           - matchLabels:
               app: mysql-qa
         regex: mysql-qa*
       containerRegex: mysql-qa*
