apiVersion: v1
kind: Secret
metadata:
  name: demo-s3-secret
type: Opaque
stringData:
  accessKey: ""
  secretKey: ""
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: demo-s3-target
spec:
  type: ObjectStore
  vendor: AWS
  objectStoreCredentials:
    bucketName: "trilioqa"
    region: "us-east-2"
    credentialSecret:
      name: demo-s3-secret
      namespace: default
  thresholdCapacity: 100Gi
