apiVersion: triliovault.trilio.io/v1
kind: Backup
metadata:
  name: postgres-full-backup-1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: Full
  backupPlan:
    name: postgres-backupplan
    namespace: postgres
