apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
 name: postgres-backupplan
 namespace: postgres
 annotations:
   argocd.argoproj.io/sync-wave: "1"
spec:
 backupNamespace: postgres
 backupConfig:
   target:
     name: demo-s3-target
     namespace: default
   schedulePolicy:
     fullBackupPolicy:
       name: trilio-daily-schedule-policy
       namespace: default
 hookConfig:
   mode: Sequential
   hooks:
     - hook:
         name: postgres-hook
       podSelector:
         labels:
           - matchLabels:
               app.kubernetes.io/name: postgresql
         regex: postgres-postgresql*
       containerRegex: postgres-postgresql*
