apiVersion: v1
kind: Secret
metadata:
  name: demo-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  accessKey: "AKIA6K7A654QRWWWCM76"
  secretKey: "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"
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: demo-s3-target
spec:
  type: ObjectStore
  vendor: AWS
  objectStoreCredentials:
    bucketName: "gitops-bucket"
    region: "us-east-2"
    credentialSecret:
      name: demo-s3-secret
  thresholdCapacity: 100Gi
