apiVersion: v1
kind: Secret
metadata:
  name: demo-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
type: Opaque
stringData:
  accessKey: "AKIA27CKLRJ32MYJBV6Q"
  secretKey: "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"
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: demo-s3-target
spec:
  type: ObjectStore
  vendor: AWS
  objectStoreCredentials:
    bucketName: "trilioqa"
    region: "us-east-2"
    credentialSecret:
      name: demo-s3-secret
  thresholdCapacity: 100Gi
